# Generated by Django 5.0.14 on 2026-07-23 14:05

import accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('ninea', models.CharField(blank=True, help_text="Numéro d'identification national des entreprises et associations.", max_length=30, verbose_name='NINEA / identifiant fiscal')),
                ('type_contribuable', models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise / PME'), ('independant', 'Travailleur indépendant'), ('commercant', 'Commerçant')], default='particulier', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="date d'inscription")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['-date_inscription'],
            },
            managers=[
                ('objects', accounts.models.UtilisateurManager()),
            ],
        ),
    ]
