# Generated by Django 5.0.14 on 2026-07-23 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieImpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': "catégorie d'impôt",
                'verbose_name_plural': "catégories d'impôt",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Impot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150, verbose_name='libellé')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='montant (FCFA)')),
                ('annee_fiscale', models.PositiveIntegerField(verbose_name='année fiscale')),
                ('date_echeance', models.DateField(verbose_name="date d'échéance")),
                ('statut', models.CharField(choices=[('impaye', 'Impayé'), ('paye', 'Payé'), ('en_retard', 'En retard')], default='impaye', max_length=15)),
                ('reference', models.CharField(max_length=30, unique=True, verbose_name='référence')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impots', to='taxes.categorieimpot', verbose_name='catégorie')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impots', to=settings.AUTH_USER_MODEL, verbose_name='contribuable')),
            ],
            options={
                'verbose_name': 'impôt',
                'verbose_name_plural': 'impôts',
                'ordering': ['-annee_fiscale', 'date_echeance'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('rappel', "Rappel d'échéance"), ('confirmation', 'Confirmation de paiement'), ('info', 'Information')], default='info', max_length=15)),
                ('lu', models.BooleanField(default=False, verbose_name='lu')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
