# Generated by Django 5.0.14 on 2026-07-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorieimpot',
            name='montant_indicatif',
            field=models.DecimalField(blank=True, decimal_places=0, help_text="Montant proposé par défaut lors d'un nouveau paiement (facultatif).", max_digits=12, null=True, verbose_name='montant indicatif (FCFA)'),
        ),
    ]
