# Generated by Django 5.0.14 on 2026-07-23 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='montant (FCFA)')),
                ('moyen', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money')], max_length=15)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué')], default='en_attente', max_length=12)),
                ('numero_telephone', models.CharField(max_length=20, verbose_name='numéro de téléphone')),
                ('reference_transaction', models.CharField(max_length=40, unique=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('impot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='taxes.impot')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-date_creation'],
            },
        ),
    ]
